version: '3.9'

services:
  app:
    build: .
    command: /usr/local/bin/usdt-monitoring-svc run service
    ports:
      - "8080:8000"
    volumes:
      - ./config.yaml:/config.yaml
    environment:
      - KV_VIPER_FILE=/config.yaml
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: USDTM
      POSTGRES_PASSWORD: rcUscL5A
      POSTGRES_DB: usdt_monitoring_db
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/nginx.conf
    depends_on:
      - app

volumes:
  db_data: